global_params:
    with_srm: True
    with_con: False
    
model_params:
    encoder: 'hrnet_w32'
    aspp_outplane: 512
    num_class: 2
    optimizer: 'sgd'
    lr: 0.001
    epoch: 100

dataset_params:
    images_dir: '/home/agency/xai/CASIA2/Tp'
    mask_dir: '/home/agency/xai/CASIA2/Gt'
    batch_size: 16
    im_size: 224
    patch_size: 14
    s_patch_len: 20
    p_patch_len: 20
    mean: [0.3948, 0.4389, 0.4421]
    std: [0.2363, 0.2205, 0.2282]
    imbalance_weight: [0.0892, 0.9108]
